// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query'
import type { AxiosError } from 'axios'

import { client } from '../client.gen'
import {
  demoGetGreeting,
  demoPutUpdateGreeting,
  type Options,
} from '../sdk.gen'
import type {
  DemoGetGreetingData,
  DemoGetGreetingResponse,
  DemoPutUpdateGreetingData,
  DemoPutUpdateGreetingResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const demoGetGreetingQueryKey = (
  options?: Options<DemoGetGreetingData>,
) => createQueryKey('demoGetGreeting', options)

export const demoGetGreetingOptions = (
  options?: Options<DemoGetGreetingData>,
) =>
  queryOptions<
    DemoGetGreetingResponse,
    AxiosError<DefaultError>,
    DemoGetGreetingResponse,
    ReturnType<typeof demoGetGreetingQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await demoGetGreeting({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: demoGetGreetingQueryKey(options),
  })

export const demoPutUpdateGreetingMutation = (
  options?: Partial<Options<DemoPutUpdateGreetingData>>,
): UseMutationOptions<
  DemoPutUpdateGreetingResponse,
  AxiosError<DefaultError>,
  Options<DemoPutUpdateGreetingData>
> => {
  const mutationOptions: UseMutationOptions<
    DemoPutUpdateGreetingResponse,
    AxiosError<DefaultError>,
    Options<DemoPutUpdateGreetingData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await demoPutUpdateGreeting({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
