// This file is auto-generated by @hey-api/openapi-ts

export { demoGetGreeting, demoPutUpdateGreeting, type Options } from './sdk.gen'
export type {
  ClientOptions,
  DemoGetGreetingData,
  DemoGetGreetingResponse,
  DemoGetGreetingResponses,
  DemoGetGreetingResultSchema,
  DemoPutUpdateGreetingBodySchema,
  DemoPutUpdateGreetingData,
  DemoPutUpdateGreetingResponse,
  DemoPutUpdateGreetingResponses,
  DemoPutUpdateGreetingResultSchema,
} from './types.gen'
