// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}

export type DemoGetGreetingResultSchema = {
  message: string
}

export type DemoPutUpdateGreetingResultSchema = {
  greeting: string
}

export type DemoPutUpdateGreetingBodySchema = {
  newGreeting: string
}

export type DemoGetGreetingData = {
  body?: never
  path?: never
  query?: never
  url: '/demo/v1/get-greeting'
}

export type DemoGetGreetingResponses = {
  /**
   * OK
   */
  200: DemoGetGreetingResultSchema
}

export type DemoGetGreetingResponse =
  DemoGetGreetingResponses[keyof DemoGetGreetingResponses]

export type DemoPutUpdateGreetingData = {
  body?: DemoPutUpdateGreetingBodySchema
  path?: never
  query?: never
  url: '/demo/v1/update-greeting'
}

export type DemoPutUpdateGreetingResponses = {
  /**
   * OK
   */
  200: DemoPutUpdateGreetingResultSchema
}

export type DemoPutUpdateGreetingResponse =
  DemoPutUpdateGreetingResponses[keyof DemoPutUpdateGreetingResponses]
