/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Express Server API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { GreetingResult } from './expressServerAPI.schemas';

import { axiosApi } from '../api/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getTestRemoteGreeting = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<GreetingResult>(
    { url: `/test-remote`, method: 'GET', ...(signal ? { signal } : {}) },
    options,
  );
};

export const getGetTestRemoteGreetingQueryKey = () => {
  return [`/test-remote`] as const;
};

export const getGetTestRemoteGreetingQueryOptions = <
  TData = Awaited<ReturnType<typeof getTestRemoteGreeting>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTestRemoteGreeting>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosApi>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTestRemoteGreetingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTestRemoteGreeting>>> = ({ signal }) =>
    getTestRemoteGreeting(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTestRemoteGreeting>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTestRemoteGreetingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTestRemoteGreeting>>
>;
export type GetTestRemoteGreetingQueryError = unknown;

export function useGetTestRemoteGreeting<
  TData = Awaited<ReturnType<typeof getTestRemoteGreeting>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTestRemoteGreeting>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTestRemoteGreeting>>,
          TError,
          Awaited<ReturnType<typeof getTestRemoteGreeting>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosApi>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTestRemoteGreeting<
  TData = Awaited<ReturnType<typeof getTestRemoteGreeting>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTestRemoteGreeting>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTestRemoteGreeting>>,
          TError,
          Awaited<ReturnType<typeof getTestRemoteGreeting>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTestRemoteGreeting<
  TData = Awaited<ReturnType<typeof getTestRemoteGreeting>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTestRemoteGreeting>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetTestRemoteGreeting<
  TData = Awaited<ReturnType<typeof getTestRemoteGreeting>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTestRemoteGreeting>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTestRemoteGreetingQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
