/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Express Server API
 * OpenAPI spec version: 1.0.0
 */
export interface DemoGetGreetingResultSchema {
  message: string
}

export interface DemoPutUpdateGreetingResultSchema {
  greeting: string
}

export interface DemoPutUpdateGreetingBodySchema {
  newGreeting: string
}
